x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./result:/opt/airflow/result
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init && \
        airflow db migrate && \
        airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin
    depends_on:
      - postgres

  webserver:
    <<: *airflow-common
    command: webserver
    environment:
      AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: 120
      AIRFLOW__WEBSERVER__WEB_SERVER_WORKERS: 2
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init

  scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - airflow-init
  
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 4g
    environment:
      SE_ENABLE_TRACING: 'false'
      SE_NODE_MAX_INSTANCES: 2
      SE_NODE_MAX_SESSIONS: 2
    ports:
      - "4444:4444"
      - "7900:7900"