SCHEMA_FIELDS_SCRAPED_DATA = [
    {'name': 'location', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'price', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'price_psf', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'top', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'remaining_lease', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'bathrooms', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'bedrooms', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'total_floor_area', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'property_type', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'model', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'floor', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'general_location', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'district', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'zone', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'region', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'street_name', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'post_code', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'furnish', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'floor_area_sqm', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'facilities_num', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'agent_id', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'agent_name', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'agent_phone_num', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'agency', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'agency_id', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'url', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'additional_information', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'transformed_date', 'type': 'DATE', 'mode': 'NULLABLE'}
]

SCHEMA_FIELDS_HISTORICAL_DATA = [
    {'name': 'date_of_sale', 'type': 'DATE', 'mode': 'NULLABLE'},
    {'name': 'year', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'month', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'general_location', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'block', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'street_name', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'price', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'top', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'remaining_lease', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'storey_range', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'total_floor_area', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'floor_area_sqm', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'model', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'property_type', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'district', 'type': 'INTEGER', 'mode': 'NULLABLE'},
    {'name': 'zone', 'type': 'STRING', 'mode': 'NULLABLE'},
    {'name': 'region', 'type': 'STRING', 'mode': 'NULLABLE'},
]